Initial public commit

diff --git a/scripts/CATS_rb_compare b/scripts/CATS_rb_compare
--- a/scripts/CATS_rb_compare
+++ b/scripts/CATS_rb_compare
@@ -69,6 +69,17 @@ check_executable () {
  done
 }
 
+#Checking R package installation (function)
+check_r_package() {
+ for R_PACKAGE in "${@}"
+ do
+  Rscript -e "if (!requireNamespace('${R_PACKAGE}', quietly=T)) quit(status=1)" >/dev/null 2>&1 || {
+   write_log ERROR "R package ${R_PACKAGE} could not be found"
+   exit 1
+  }
+ done
+}
+
 #Checking the supplied files (function)
 check_files() {
  for FILE in "${@}"
@@ -132,7 +143,10 @@ test_numeric_arg () {
 }
 
 #Checking executable requirements
-check_executable Rscript
+check_executable Rscript pandoc
+
+#Checking R package requirements
+check_r_package rmarkdown knitr data.table ggplot2 ggdist GenomicRanges Matrix igraph UpSetR ggVennDiagram egg ComplexHeatmap GenomeInfoDb GenomicDistributions
 
 #Defining default parameters
 STRANDED="F"
diff --git a/scripts/CATS_rb_map b/scripts/CATS_rb_map
--- a/scripts/CATS_rb_map
+++ b/scripts/CATS_rb_map
@@ -39,6 +39,17 @@ check_executable () {
  done
 }
 
+#Checking R package installation (function)
+check_r_package() {
+ for R_PACKAGE in "${@}"
+ do
+  Rscript -e "if (!requireNamespace('${R_PACKAGE}', quietly=T)) quit(status=1)" >/dev/null 2>&1 || {
+   write_log ERROR "R package ${R_PACKAGE} could not be found"
+   exit 1
+  }
+ done
+}
+
 #Checking the supplied directories (function)
 check_directories() {
  for DIRECTORY in "${@}"
@@ -102,7 +113,10 @@ test_numeric_arg () {
 }
 
 #Checking executable requirements
-check_executable R spaln
+check_executable Rscript spaln
+
+#Checking R package requirements
+check_r_package data.table
 
 #Defining default parameters
 STRANDNESS=3
